name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --emptyOutDir

      - name: Verify build folder
        run: |
          ls -la dist
          cat dist/index.html | grep assets || echo "ВНИМАНИЕ: Сборка не удалась!"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
